vich_uploader:
    db_driver: orm

    mappings:
        cryptocurrency_image:
            uri_prefix: /images/cryptocurrencies
            upload_destination: '%kernel.project_dir%/public/images/cryptocurrencies'
            namer: Vich\UploaderBundle\Naming\UniqidNamer